### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by batarian71** [catalyst-app/Catalyst#11]
Hi. I am a graphic designer. I would like to volunteer to design a logo for this repository that you can use in the readme file. What do you say?

**Comment by Fauxil-Fox** [comment]
Hey!

I appreciate your interest and willingness to help with our project, however, we already have a logo and many other graphical assets.

However, if at some point in the future we need any graphic design, we'll let you know!  

Feel free to join our [mailing list on our site](https://catalystapp.co/#email-list-addition-form-form-element), [Discord server](https://discord.gg/EECUcnT), or [Telegram group](https://t.me/catalystapp)!

Thanks,
Fauxil
