### ISSUE TITLE
Additional features

### ISSUE THREAD

**Issue by ncovercash** [catalyst-app/Catalyst#4]
**User Account**  

- [ ] Email verification timeout
- [ ] Password reset
- [ ] Better suspended/disabled notice
- [ ] Integration Profile Photos
- [ ] Reporting spam/fake/stolen/inappropriate
- [ ] Blob-based uploading (show inline)
- [ ] Social media URL form things
- [ ] Drag and drop uploading
- [ ] Let artists write reviews for buyers
- [ ] Example account

**Dashboard/User Profile**  

- [ ] Statistics
- [ ] Badges

**Characters**  

- [ ] Blob-based uploading (show inline)
- [ ] Report spam/fake/stolen/inappropriate
- [ ] Drag and drop uploading
- [ ] Sharing
- [ ] URL access?
- [ ] Example character

**Artists**  

- [ ] Streaming
- [ ] Trello integration
- [ ] Report spam/fake/inappropriate
- [ ] Statistics
- [ ] Send message to those who are watching (have added to wishlist)
- [ ] Statistics for money made
- [ ] Social media URL form things
- [ ] Badges
  - [ ] Verification
- [ ] Experience levels
  - [ ] From reviews?
- [ ] Example page

**Commission Types**  

- [ ] Analytics
- [ ] Trello
- [ ] Direct links
- [ ] Payments
  - [ ] Suggested types
  - [ ] Fee calculators
- [ ] Report spam
- [ ] Schedule opening
- [ ] Slot numbers
- [ ] Writers
- [ ] Example

**Commission**  

- [ ] PayPal cart integration/invoice
- [ ] integration upload
- [ ] Sharing
- [ ] Trello
  - [ ] Access control
- [ ] Blob-based uploading (show inline)
- [ ] Drag and drop uploading
- [ ] Message which it concerns
- [ ] Review flagging
- [ ] Review reply
- [ ] Report
  - [ ] Harrassment
  - [ ] Spam
  - [ ] Scam/fraud
- [ ] Examples
  - [ ] Start
  - [ ] Middle
  - [ ] Review

**Search**  

- [ ] Better syntax (AND, OR, XOR, basic boolean ops)

**Universal**  

- [ ] SFW button (like FA's)
- [ ] Messaging "concerning" attr
- [ ] Pretty 404's
- [ ] Handle input error messages better
- [ ] Messages to email
- [ ] Dark theme
- [ ] Import images from FA and similar
- [ ] Localization
- [ ] Reporting of broken site and such
- [ ] Blacklisting attrs

**Easter eggs**  

- [x] Konami-style bulge
- [ ] Confetti button
- [ ] Some fun about page stuff

# Potential Optimizations

- [x] Single user SQL fetch on normal page load
  - [ ] API calls should not use this

**Comment by smileytechguy** [comment]
@smileytechguy test
